/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef netplay_CONSTANTS_H
#define netplay_CONSTANTS_H

#include "netplay_types.h"

namespace netplay { namespace thrift {

class netplayConstants {
 public:
  netplayConstants();

};

extern const netplayConstants g_netplay_constants;

}} // namespace

#endif
