/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "netplay_constants.h"

namespace netplay { namespace thrift {

const netplayConstants g_netplay_constants;

netplayConstants::netplayConstants() {
}

}} // namespace

